apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-azure-storage
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: azure-storage
    creationPolicy: Owner
  data:
    - secretKey: ACCOUNT_NAME
      remoteRef:
        key: azure-storage-account-name
    - secretKey: ACCOUNT_KEY
      remoteRef:
        key: azure-storage-account-key

