apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-db
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: supabase-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: pg-username
    - secretKey: password
      remoteRef:
        key: pg-password
    - secretKey: database
      remoteRef:
        key: pg-database

