apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-secrets
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: supabase-env
  data:
  - secretKey: POSTGRES_CONNECTION_STRING
    remoteRef:
      key: postgres-connection-string
  - secretKey: JWT_SECRET
    remoteRef:
      key: jwt-secret
  - secretKey: ANON_KEY
    remoteRef:
      key: anon-key
  - secretKey: SERVICE_ROLE_KEY
    remoteRef:
      key: service-role-key
  - secretKey: STORAGE_CONNECTION_STRING
    remoteRef:
      key: storage-connection-string
