apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-storage-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: supabase-storage-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: supabase-storage-creds
