name: Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CDKTF CLI
        run: npm i -g cdktf-cli

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install constructs cdktf jsii typeguard cdktf-cdktf-provider-azurerm

      - name: Destroy infra
        shell: pwsh
        env:
          TFVARS_FILE: vars/dev.tfvars
          PG_ADMIN_LOGIN: placeholder
          PG_ADMIN_PASSWORD: placeholder
        run: ./scripts/90-destroy-infra.ps1

